language: rust

rust:
  - stable
  - beta
  - nightly

script: make ci

cache:
  cargo: true

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    on_success: never
